### ISSUE TITLE
Build: error[E0599]: no associated item named `EPSILON` found for type `f32` in the current scope

### ISSUE THREAD

**Issue by vv181** [romanz/electrs#434]
**Which command failed?**
`$ ROCKSDB_INCLUDE_DIR=/usr/include ROCKSDB_LIB_DIR=/usr/lib cargo build --locked --no-default-features --release
`

**What was the error message?**
```
 Compiling electrs v0.8.10 (~snip)
error[E0599]: no associated item named `EPSILON` found for type `f32` in the current scope
   --> src/mempool.rs:271:83
    |
271 |         if bin_size > VSIZE_BIN_WIDTH && (last_fee_rate - fee_rate).abs() >= f32::EPSILON {
    |                                                                                   ^^^^^^^ associated item not found in `f32`
    |
help: you are looking for the module in `std`, not the primitive type
    |
271 |         if bin_size > VSIZE_BIN_WIDTH && (last_fee_rate - fee_rate).abs() >= std::f32::EPSILON {
    |                                                                              ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `electrs`.

To learn more, run the command again with --verbose.
```

</details>

**System**
OS name and version: Arch
rustc version: 1.41.1 (f3e1a954d 2020-02-24)
cargo version: 1.41.0 (626f0f40e 2019-12-03)

**Compilation**
Linking: dynamic
Cross compilation: no
Target architecture: x86_64

**Comment by Kixunil** [comment]
This was clearly broken by https://github.com/romanz/electrs/commit/39dce7693d694b21514637a234b2089df6e68157

How the hell did that commit happen? CI should catch that. Also does @tcharding have direct push access to this repository?

**Comment by Kixunil** [comment]
Let's see if #435 catches it.

**Comment by Kixunil** [comment]
Just learned a few things about floating point comparison and thinking that we may want to replace `f32` with `fraction::Ratio<u64>` or something similar to avoid the issues completely. Not sure how important it is.

**Comment by romanz** [comment]
Let's keep if `f32` for now, it'll be deprecated after the 0.9 release.
