### ISSUE TITLE
Error updating: error[E0658]: non-builtin inner attributes are unstable

### ISSUE THREAD

**Issue by Genbel** [romanz/electrs#300]
Hi, after update two weeks ago, today I tried to update electrs repository again and I got that error (I updated following these tutorial, upgrade block: https://stadicus.github.io/RaspiBolt/raspibolt_55_explorer.html)

**$ cargo build --release**
```
   Compiling protobuf v2.17.0
   Compiling serde_json v1.0.57
   Compiling cc v1.0.60
   Compiling backtrace v0.3.50
error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/descriptor.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/plugin.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/rustproto.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/any.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/api.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/duration.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/empty.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/field_mask.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/source_context.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/struct_pb.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/timestamp.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/type_pb.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error[E0658]: non-builtin inner attributes are unstable
 --> /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/wrappers.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726

error: aborting due to 13 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `protobuf`.
warning: build failed, waiting for other jobs to finish...
error: build failed

```
Also tried to install another package but not success

**$ apt-get install protobuf-compiler**

**Comment by Kixunil** [comment]
Which version of Rust do you use?

**Comment by Genbel** [comment]
Hi! I was using 1.44 but now I just updated as you give me some clue and it compiles the binary perfectly :). Actual version is the stable one: 1.46.0
One question, sometimes I have in the logs of electrs this kind of output, what does it mean?
[tx_1,..., tx_n]: getrawtransaction RPC error: {"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."}

Thanks for your time ;)

**Comment by Kixunil** [comment]
That's strange, it should work with  as low as 1.34. This will need to be inspected.

AFAIK that error message means that either you forgot to turn pruning off or you have corrupted data (did your bitcoind crash/was killed in the past?). You'll need to run `bitcoind` with `-reindex` to fix it. Unfortunately, this will take about the same time as IBD.

**Comment by Genbel** [comment]
Is there any command to see if my bitcoin core is corrupted?

**Comment by Kixunil** [comment]
I don't think there is. If you know the txid you could look up the block hash it was mined in via block explorer (using Tor) and then try issue `bitcoin-cli getrawtransaction TXID BLOCKHASH`. If the call fails with the same message, it's very likely the data is corrupted.

Anyway, I think that log message could be improved to provide more information for analysis. I'm not sure if `electrs` was trying to look up mempool or confirmed transaction.

**Comment by Genbel** [comment]
ok thanks! If I will get again that error, I will come with the feed back

Thanks for your time ;)

**Comment by Kixunil** [comment]
See also #321
