### ISSUE TITLE
Dynamic linking rocksdb on `p2p` branch

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#469]
Currently, `p2p` branch depends on rocksdb 6.15.4 (https://github.com/romanz/rust-rocksdb/commits/2021-05/electrs-build).
I am not sure whether [rocksdb dynamic linking](https://github.com/romanz/electrs/blob/p2p/doc/usage.md#dynamic-linking) will work on Debian buster ([which has 5.17.2](https://packages.debian.org/buster/librocksdb-dev)) or on bullseye ([which has 6.11.4](https://packages.debian.org/bullseye/librocksdb-dev)).

@Kixunil What do you think would be the best approach for [the 0.9 version](https://github.com/romanz/electrs/pull/466)?

**Comment by Kixunil** [comment]
Good question. I will try to build it soon on both and see how it goes. It'd be nice if we could figure out how to link it in Buster (for people who are slower to upgrade) but ultimately, *for me* it's not a huge deal if it only works on Bullseye. I want to migrate to Bullseye quite soon anyway. If neither woks then at least we should try to make build deterministic.

**Comment by Pantamis** [comment]
When I tried to build with dynamic linking one-two months ago on RaspberryPi OS 64-bits it didn't work and I think the problem was related to rocksdb.

**Comment by Kixunil** [comment]
I tried to follow our guide on bullseye to see what happens. It failed.

<details>
<summary>Error output</summary>

```
error[E0425]: cannot find function `rocksdb_env_set_low_priority_background_threads` in crate `ffi`
   --> /home/user/.cargo/git/checkouts/rust-rocksdb-949349bba4a70d36/4554d19/src/db_options.rs:144:18
    |
144 |             ffi::rocksdb_env_set_low_priority_background_threads(self.inner, n);
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `rocksdb_env_set_high_priority_background_threads`
    | 
   ::: /home/user/electrs/target/release/build/librocksdb-sys-700d271c0486bc04/out/bindings.rs:3:83272
    |
3   | ...tern "C" { pub fn rocksdb_env_set_high_priority_background_threads (env : * mut rocksdb_env_t , n : libc :: c_int) ; } extern "C" { pu...
    |               --------------------------------------------------------------------------------------------------------- similarly named function `rocksdb_env_set_high_priority_background_threads` defined here

error[E0425]: cannot find function `rocksdb_env_set_bottom_priority_background_threads` in crate `ffi`
   --> /home/user/.cargo/git/checkouts/rust-rocksdb-949349bba4a70d36/4554d19/src/db_options.rs:152:18
    |
152 |             ffi::rocksdb_env_set_bottom_priority_background_threads(self.inner, n);
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `rocksdb_env_set_high_priority_background_threads`
    | 
   ::: /home/user/electrs/target/release/build/librocksdb-sys-700d271c0486bc04/out/bindings.rs:3:83272
    |
3   | ...tern "C" { pub fn rocksdb_env_set_high_priority_background_threads (env : * mut rocksdb_env_t , n : libc :: c_int) ; } extern "C" { pu...
    |               --------------------------------------------------------------------------------------------------------- similarly named function `rocksdb_env_set_high_priority_background_threads` defined here

error[E0425]: cannot find function `rocksdb_options_set_stats_persist_period_sec` in crate `ffi`
    --> /home/user/.cargo/git/checkouts/rust-rocksdb-949349bba4a70d36/4554d19/src/db_options.rs:2256:18
     |
2256 |             ffi::rocksdb_options_set_stats_persist_period_sec(self.inner, period);
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `rocksdb_options_set_stats_dump_period_sec`
     | 
    ::: /home/user/electrs/target/release/build/librocksdb-sys-700d271c0486bc04/out/bindings.rs:3:61865
     |
3    | ...tern "C" { pub fn rocksdb_options_set_stats_dump_period_sec (arg1 : * mut rocksdb_options_t , arg2 : libc :: c_uint) ; } extern "C" { ...
     |               ----------------------------------------------------------------------------------------------------------- similarly named function `rocksdb_options_set_stats_dump_period_sec` defined here
```

</details>

Would it be a too big issue to downgrade a bit? I'll look into minimum necessary downgrade soon.

**Comment by romanz** [comment]
Thanks for testing - I have opened https://github.com/romanz/electrs/pull/473, please take a look :)

**Comment by romanz** [comment]
> I tried to follow our guide on bullseye to see what happens. It failed.

I think it should be resolved now by https://github.com/romanz/rust-rocksdb/commit/2023b18a7b83fc47b5bc950b5322a2284b771162 (tested locally on Debian 11 docker image):

```
$ docker run --rm -it debian:bullseye-slim /bin/bash
# apt update && apt install cargo clang librocksdb-dev git
# git clone -b p2p-rocksdb-6.11.4 https://github.com/romanz/electrs && cd electrs/
# ROCKSDB_INCLUDE_DIR=/usr/include ROCKSDB_LIB_DIR=/usr/lib cargo build --locked --no-default-features --release
   <snip>
   Compiling secp256k1-sys v0.4.1
   Compiling librocksdb-sys v6.11.4 (https://github.com/romanz/rust-rocksdb?rev=2023b18a7b83fc47b5bc950b5322a2284b771162#2023b18a)
   Compiling rocksdb v0.15.0 (https://github.com/romanz/rust-rocksdb?rev=2023b18a7b83fc47b5bc950b5322a2284b771162#2023b18a)
   Compiling toml v0.5.8
   Compiling secp256k1 v0.20.3
   Compiling bitcoin_hashes v0.10.0
   Compiling cargo_toml v0.8.1
   Compiling configure_me v0.4.0
   Compiling jsonrpc v0.12.0
   Compiling bitcoin v0.27.0
   Compiling bitcoincore-rpc-json v0.13.0 (https://github.com/romanz/rust-bitcoincore-rpc?rev=06ac9fa3e834413f7afeaed322cf8098d876e4a0#06ac9fa3)
   Compiling bitcoincore-rpc v0.13.0 (https://github.com/romanz/rust-bitcoincore-rpc?rev=06ac9fa3e834413f7afeaed322cf8098d876e4a0#06ac9fa3)
   Compiling electrs v0.9.0-rc1 (/electrs)
    Finished release [optimized] target(s) in 2m 17s
```

**Comment by Kixunil** [comment]
Awesome! Something got into my testing so can't do it that soon, hopefully not later than tomorrow.

I wonder if this could be conditional and possibly upstreamed (although somewhat strange?). I started thinking lately about best way to make dependencies as compatible across ranges as reasonable but didn't go far with my thinking yet. :)

**Comment by romanz** [comment]
BTW, [Ubuntu 21.04](https://packages.ubuntu.com/hirsute/librocksdb-dev) also has RocksDB 6.11.4.

**Comment by romanz** [comment]
#473 was tested on Debian 11 and Ubuntu 21.04 and merged, so this issue can be closed.
