### ISSUE TITLE
Docker build fails with error[E0505]

### ISSUE THREAD

**Issue by algotechio** [romanz/electrs#180]
During the build of the docker image, the following error appears.  I googled the error extensively, but did not find any reference to it.

```  
...
Compiling stderrlog v0.4.1
Compiling rayon v1.2.0
Compiling cc v1.0.26
Compiling configure_me v0.3.3
error[E0505]: cannot move out of `string` because it is borrowed
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/configure_me_codegen-0.3.9/src/config.rs:58:25
   |
55 |             for (i, c) in string.chars().enumerate() {
   |                           ------ borrow of `string` occurs here
...
58 |                         string,
   |                         ^^^^^^ move out of `string` occurs here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0505`.
error: Could not compile `configure_me_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```

**Comment by Kixunil** [comment]
I just noticed this by accident and the code comes from my library. Since the code compiles on my computer and I use Rust 1.36 and the docker 1.34, I guess I accidentally introduced backwards-incompatibility.

@romanz Is it possible to upgrade Docker? I'll look if there's an easy fix anyway, upgrading Rust might be easier though.

**Comment by Kixunil** [comment]
I figured out what's wrong, see the linked issue for more detail. I believe updating Rust is just better, but willing to help by changing the code if older version is much needed.

**Comment by romanz** [comment]
The issue here is that Rust 1.34 is the one supported by latest stable Debian, so if possible I would prefer to keep electrs to support it...
WDYT?

**Comment by Kixunil** [comment]
OK, I will patch the code.

**Comment by Kixunil** [comment]
I figured out a nice way to solve the issue in library, but tests still fail to compile. Is it good enough for electrs?

**Comment by Kixunil** [comment]
Ah, not really, the generated code is still problematic. :(

I guess, I'll try to switch to 2018

**Comment by Kixunil** [comment]
The generated code still requires NLL, but that should be fine, since electrs uses 2018 edition.

**Comment by romanz** [comment]
I think that I'll move to latest Rust (when async/await lands on stable) :)

**Comment by Kixunil** [comment]
@algotechio it's fixed now, let me know if there's any other problem.
